openapi: "3.0.1"
info:
  title: Users Service API
  description: Users Microservice of Message in a Bottle Application
  version: "0.1"

servers:
  - url: /

paths:
  /blacklist/{blocked_id}/{blocking_id}:
    put:
      summary: Create a new block relationship
      tags: [ Blacklist ]
      operationId: mib.resources.blacklist.block
      parameters:
        - name: blocked_id
          description: User Blocked Unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: blocking_id
          description: User Blocking Unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Relationship created
        409:
          description: Relantionship already exists
        default:
          description: An error occured during the block
    
    post:
      summary: Delete a block relationship
      tags: [ Blacklist ]
      operationId: mib.resources.blacklist.unblock
      parameters:
        - name: blocked_id
          description: User Unblocked Unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: blocking_id
          description: User Unblocking Unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Relationship deleted
        404:
          description: Relantionship not exists
        default:
          description: An error occured during the unblock
    
  /blocked_users/{user_id}:
    get:
      summary: Get all relationships for a user by its id
      tags: [ Blacklist ]
      operationId: mib.resources.blacklist.get_blocked_users
      parameters:
        - name: user_id
          description: User Unique ID
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Blocked users list 
        default:
          description: An error occured while retrieving the list

components:
  schemas:
    Blacklist:
      required:
        - id_user
        - id_blocked
      type: object
      properties:
        id_user:
          type: integer
          format: int64
          description: id of the user (un)blocking
          example: 1
        id_blocked:
          type: integer
          format: int64
          description: id of the user being (un)blocked
          example: 2